// Session types
export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const CLEAR_SESSION_ERROR = "CLEAR_SESSION_ERROR";
export const RECEIVE_SESSION_ERROR = "RECEIVE_SESSION_ERROR";

// Data type
export const RECEIVE_GENERAL_NEWS = "RECEIVE_GENERL_NEWS";
export const CLEAR_GENERAL_NEWS = "CLEAR_GENERAL_NEWS";
export const RECEIVE_GENERAL_NEWS_ERROR = "RECEIVE_GENERAL_NEWS_ERROR";
export const CLEAR_GENERAL_NEWS_ERROR = "CLEAR_GENERAL_NEWS_ERROR";

export const RECEIVE_WATCHLIST_DATA = "RECEIVE_WATCHLIST_DATA" ;
export const CLEAR_WATCHLIST_DATA = "CLEAR_WATCHLIST_DATA";
export const RECEIVE_WATCHLIST_ERROR = "RECEIVE_WATCHLIST_ERROR";
export const CLEAR_WATCHLIST_ERROR = "CLEAR_WATCHLIST_ERROR";

export const RECEIVE_OWNED_STOCKS_DATA = "RECEIVE_OWNED_STOCKS_DATA";
export const CLEAR_OWNED_STOCKS_DATA = "CLEAR_OWNED_STOCKS_DATA";
export const RECEIVE_OWNED_STOCKS_ERROR = "RECEIVE_OWNED_STOCKS_ERROR";
export const CLEAR_OWNED_STOCKS_ERROR = "CLEAR_OWNED_STOCKS_ERROR";