// Session types
export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const CLEAR_SESSION_ERROR = "CLEAR_SESSION_ERROR";
export const RECEIVE_SESSION_ERROR = "RECEIVE_SESSION_ERROR";

// Data type
export const RECEIVE_WATCHLIST_DATA = "RECEIVE_WATCHLIST_DATA" ;
export const CLEAR_WATCHLIST_DATA = "CLEAR_WATCHLIST_DATA";
export const RECEIVE_WATCHLIST_ERROR = "RECEIVE_WATCHLIST_ERROR";
export const CLEAR_WATCHLIST_ERROR = "CLEAR_WATCHLIST_ERROR";

export const RECEIVE_OWNED_STOCKS_DATA = "RECEIVE_OWNED_STOCKS_DATA";
export const CLEAR_OWNED_STOCKS_DATA = "CLEAR_OWNED_STOCKS_DATA";
export const RECEIVE_OWNED_STOCKS_ERROR = "RECEIVE_OWNED_STOCKS_ERROR";
export const CLEAR_OWNED_STOCKS_ERROR = "CLEAR_OWNED_STOCKS_ERROR";

export const RECEIVE_SEARCH_RESULTS = "RECEIVE_SEARCH_RESULTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS" ;
export const RECEIVE_SEARCH_ERROR = "RECEIVE_SEARCH_ERROR";
export const CLEAR_SEARCH_ERROR = "CLEAR_SEARCH_ERROR";

export const RECEIVE_STOCKINFO = "RECEIVE_STOCKINFO";
export const CLEAR_STOCKINFO = "CLEAR_STOCKINFO";
export const RECEIVE_STOCKINFO_ERROR = "RECEIVE_STOCKINFO_ERROR";
export const CLEAR_STOCKINFO_ERROR = "CLEAR_STOCKINFO_ERROR";
// Portfolio type